version: 1.1-SNAPSHOT
# enter the inactivity of all players in a town in hours before it will be deleted
inactiveLength: 336 # 14 days
# how often will the server be checked for inactive towns? (minutes)
interval: 60
# exempt towns
exemptions: ["Example_Town"]